BITCOIN_RPC_HOST: 127.0.0.1
BITCOIN_RPC_USER: bitcoin
BITCOIN_RPC_PASSWORD: changeme
BITCOIN_RPC_PORT: 8332
BITCOIN_RPC_TIMEOUT: 3000

DB_DIALECT: sqlite
# DB_DIALECT: postgres
# DB_PROTOCOL: postgres
# DB_USER: user
# DB_PASSWORD: password
# DB_DATABASE: cashmunity
# DB_HOST: 127.0.0.1
# DB_PORT: 5432
